CLASS zcl_236_intro DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_236_intro IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

    DATA: var TYPE /LRN/S4D430_IND_CDS_View.


    SELECT FROM /LRN/S4D430_IND_CDS_View  FIELDS * INTO TABLE @DATA(result).
    out->write( result ).



  ENDMETHOD.
ENDCLASS.
